export const TYPE = {
    //PRODUCTS
    SAGA_GET_PRODUCTS:'SAGA_GET_PRODUCTS',
    SET_PRODUCTS:'SET_PRODUCTS',

    //CATEGORIES
    SAGA_GET_CATEGORIES:'SAGA_GET_CATEGORIES',
    SET_CATEGORIES:'SET_CATEGORIES',
};
