export const TYPE = {
    //PRODUCTS
    SAGA_GET_PRODUCTS:'SAGA_GET_PRODUCTS',
    SET_PRODUCTS:'SET_PRODUCTS',
    SET_FINDED_PRODUCTS:'SET_FINDED_PRODUCTS',

    //CATEGORIES
    SAGA_GET_CATEGORIES:'SAGA_GET_CATEGORIES',
    SET_CATEGORIES:'SET_CATEGORIES',

    //CART
    ADD_CART_ITEM:'ADD_CART_ITEM',
    CHNAGE_TOTAL_CART_PRODUCTS:'CHNAGE_TOTAL_CART_PRODUCTS',
};
